### PR TITLE
Feature/random hex

### LINKED ISSUE #5: Iteration 1 getRandomHex() {}
## JS
- Get random color & Number `function getRandomHex() {}`
- https://github.com/SethBurns/coloRandom/pull/2

### PR DESCRIPTION
**Pull request by jalbe0076**
This pull request features a new hex randomizer function. The function was tested using a console log to review the randomizing numbers and it was also tested by hardcoding the number to get the maximum range that gets passed to the `toString` method. Please review. 

This pull request will close #5

### CODE REVIEW

**Review by SethBurns — APPROVED** [review]
Looks solid, Seth approves for a merge.

**Review by mbenfowler — CHANGES_REQUESTED** [review]
Looks like we are running into cases where we don't have enough digits in our hex!  Please add a function that adds zeros to the front of any hex we get from here, or research a whole new way to avoid this!

Screenshot 2023-04-11 at 7 01 29 PM

**Comment by jalbe0076** [comment]
testing comment field

**Comment by jalbe0076** [comment]
> Looks like we are running into cases where we don't have enough digits in our hex! Please add a function that adds zeros to the front of any hex we get from here, or research a whole new way to avoid this!
> 
> Screenshot 2023-04-11 at 7 01 29 PM

Researched issue with returning 5 digits. leading 0's are removed, added fix with `padStart` method forcing it to ensure there are a minimum of 6 digits and to add 0's to the start if less than 5. 
Fixed the other issue where #FFFFFF would never display because `Math.random` will never randomize to 1. Fix was applied by increasing the total amount of hex colours by 1.

**Review by mbenfowler — APPROVED** [review]
lit

**Comment by SethBurns** [comment]
So clean. 😌

**Pull request merged**
